development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: railsfox_development
  pool:     5
  # SeedVantageDBA
  username: sampleuser
  password: password

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: app_production
  pool:     5
  # SeedVantageDBA
  username: sampleuser
  password: password

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: railsfox_test
  pool:     5
  username: sampleuser
  password: password
